# Generated by Django 4.2.30 on 2026-07-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('org_type', models.CharField(choices=[('vendor', 'Vendor'), ('institute', 'Training Institute'), ('client_company', 'Client Company'), ('partner', 'Partner'), ('investor_company', 'Investor Company'), ('other', 'Other')], default='other', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('firestore_vendor_id', models.CharField(blank=True, help_text='inv_vendors doc ID', max_length=255)),
                ('firestore_institute_id', models.CharField(blank=True, help_text='trn_institutes doc ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('alt_phone', models.CharField(blank=True, max_length=50)),
                ('person_type', models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('trainer', 'Trainer'), ('client', 'Client'), ('vendor_contact', 'Vendor Contact'), ('investor', 'Investor'), ('stakeholder', 'Stakeholder'), ('candidate', 'Candidate'), ('other', 'Other')], default='other', max_length=30)),
                ('roles', models.JSONField(blank=True, default=list, help_text='Additional roles across modules')),
                ('firestore_contact_id', models.CharField(blank=True, help_text='sys_contacts doc ID', max_length=255)),
                ('firestore_employee_id', models.CharField(blank=True, help_text='hrm_employees doc ID', max_length=255)),
                ('firestore_student_id', models.CharField(blank=True, help_text='trn_registrations doc ID', max_length=255)),
                ('firestore_investor_id', models.CharField(blank=True, help_text='invst_investors doc ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registry_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='registry.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='registry.person')),
            ],
            options={
                'verbose_name_plural': 'Person-Organization Links',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='registry_or_name_88a0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='registry_or_org_typ_33db30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personorganization',
            unique_together={('person', 'organization', 'role')},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['email'], name='registry_pe_email_62fa34_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['person_type'], name='registry_pe_person__7faa93_idx'),
        ),
    ]
