# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_organization_created_by_organization_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='firestore_contact_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firestore_employee_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firestore_investor_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='firestore_student_id',
        ),
    ]
