# Generated by Django 5.0.14 on 2026-07-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_person_firestore_contact_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='firestore_institute_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='firestore_vendor_id',
        ),
    ]
