# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittrail',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='vendorbill',
            name='firestore_id',
        ),
    ]
