# Generated by Django 5.2.15 on 2026-07-09 09:04

import django.db.models.deletion
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_keyposition_successionplan_notificationpreference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Behavioral', 'Behavioral'), ('Leadership', 'Leadership'), ('Functional', 'Functional')], default='Technical', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Competency',
                'verbose_name_plural': 'Competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Collaboration', 'Collaboration'), ('Communication', 'Communication'), ('Leadership', 'Leadership'), ('Technical', 'Technical Skills'), ('Reliability', 'Reliability'), ('Innovation', 'Innovation'), ('Culture', 'Culture Fit'), ('General', 'General')], default='General', max_length=50)),
                ('question_text', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback Question',
                'verbose_name_plural': 'Feedback Questions',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='ec_tertiary_mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Third Emergency - Mobile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ec_tertiary_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Third Emergency - Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ec_tertiary_relation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Third Emergency - Relation'),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Candidate rating (1-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='hrm/resumes/'),
        ),
        migrations.AddField(
            model_name='recruitmentcandidate',
            name='source',
            field=models.CharField(blank=True, choices=[('LinkedIn', 'LinkedIn'), ('Job Board', 'Job Board'), ('Referral', 'Referral'), ('Company Website', 'Company Website'), ('Agency', 'Agency'), ('Social Media', 'Social Media'), ('Campus', 'Campus Recruitment'), ('Walk-in', 'Walk-in'), ('Other', 'Other')], help_text='Sourcing channel', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100, null=True, verbose_name='National ID')),
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('cover_letter', 'Cover Letter'), ('certificate', 'Certificate'), ('id_proof', 'ID Proof'), ('reference', 'Reference Letter'), ('other', 'Other')], default='resume', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='hrm/candidate_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hrm.recruitmentcandidate')),
            ],
            options={
                'verbose_name': 'Candidate Document',
                'verbose_name_plural': 'Candidate Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('visa', 'Visa Renewal'), ('work_permit', 'Work Permit'), ('contract', 'Contract Renewal'), ('certification', 'Certification Renewal'), ('probation', 'Probation Review'), ('medical', 'Medical Checkup'), ('training', 'Mandatory Training'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Due', 'Due'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Upcoming', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reminders', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Compliance Reminder',
                'verbose_name_plural': 'Compliance Reminders',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=255)),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education Histories',
                'ordering': ['-end_year', 'degree'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EngagementSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_anonymous', models.BooleanField(default=False, help_text='Responses are anonymous')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Closed', 'Closed')], default='Draft', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement Survey',
                'verbose_name_plural': 'Engagement Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(blank=True, default='', help_text='Manager / Peer / Subordinate / Self', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to='hrm.reviewcycle')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='hrm.employee')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '360 Feedback Request',
                'verbose_name_plural': '360 Feedback Requests',
                'ordering': ['-created_at'],
                'unique_together': {('reviewer', 'reviewee', 'review_cycle')},
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-5)'), ('text', 'Text'), ('multiple_choice', 'Multiple Choice'), ('yes_no', 'Yes/No')], default='rating', max_length=50)),
                ('options_json', models.JSONField(blank=True, default=list, help_text='Options for multiple_choice')),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='hrm.engagementsurvey')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TalentReviewMeeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Completed', 'Completed')], default='Draft', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talent Review Meeting',
                'verbose_name_plural': 'Talent Review Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Needs Improvement'), (2, '2 - Developing'), (3, '3 - Proficient'), (4, '4 - Advanced'), (5, '5 - Expert')])),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='hrm.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Competency Rating',
                'verbose_name_plural': 'Competency Ratings',
                'ordering': ['-assessment_date'],
                'unique_together': {('employee', 'competency', 'assessment_date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=50)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hrm.employee')),
            ],
            options={
                'verbose_name': 'Employee Skill',
                'verbose_name_plural': 'Employee Skills',
                'ordering': ['employee', '-proficiency'],
                'unique_together': {('employee', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('response_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hrm.feedbackquestion')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hrm.feedbackrequest')),
            ],
            options={
                'verbose_name': 'Feedback Response',
                'verbose_name_plural': 'Feedback Responses',
                'ordering': ['request', 'question__order'],
                'unique_together': {('request', 'question')},
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_text', models.TextField(blank=True, default='')),
                ('response_value', models.IntegerField(blank=True, help_text='Numeric rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='hrm.employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hrm.surveyquestion')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hrm.engagementsurvey')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['survey', 'question'],
                'unique_together': {('survey', 'question', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='NineBoxCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('performance', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('potential', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine_box_ratings', to='hrm.employee')),
                ('talent_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nine_box_cells', to='hrm.talentreviewmeeting')),
            ],
            options={
                'verbose_name': '9-Box Cell',
                'verbose_name_plural': '9-Box Cells',
                'ordering': ['talent_review', 'employee'],
                'unique_together': {('talent_review', 'employee')},
            },
        ),
    ]
