# Generated by Django 5.2.15 on 2026-07-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_competency_feedbackquestion_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliancereminder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
