# Generated by Django 5.2.15 on 2026-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_alter_compliancereminder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementsurvey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='engagementsurvey',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
