# Generated by Django 4.2.30 on 2026-07-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_alter_engagementsurvey_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_to',
            field=models.ForeignKey(blank=True, help_text='The manager/supervisor this employee reports to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hrm.employee'),
        ),
    ]
