# Generated by Django 4.2.30 on 2026-07-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_employee_reporting_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalary',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deducted', 'Deducted')], default='Pending', max_length=50),
        ),
    ]
