# Generated by Django 4.2.30 on 2026-07-09 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0009_alter_advancesalary_status_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('Verbal Warning', 'Verbal Warning'), ('Written Warning', 'Written Warning'), ('Final Written Warning', 'Final Written Warning'), ('Suspension', 'Suspension'), ('Pay Cut', 'Pay Cut'), ('Demotion', 'Demotion'), ('Termination', 'Termination'), ('Other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('issued_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, help_text='For warnings/suspensions with limited duration', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Issued', 'Issued'), ('Under Appeal', 'Under Appeal'), ('Enforced', 'Enforced'), ('Overturned', 'Overturned')], default='Pending', max_length=20)),
                ('supporting_document', models.TextField(blank=True, default='', help_text='URL or reference to supporting document')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disciplinary Action',
                'verbose_name_plural': 'Disciplinary Actions',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('incident_date', models.DateField()),
                ('nature_of_offense', models.TextField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Gross', 'Gross Misconduct')], default='Minor', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Under Investigation', 'Under Investigation'), ('Hearing Scheduled', 'Hearing Scheduled'), ('Resolved', 'Resolved'), ('Dismissed', 'Dismissed')], default='Open', max_length=30)),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_cases', to='hrm.employee')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disciplinary Case',
                'verbose_name_plural': 'Disciplinary Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryHearing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hearing_date', models.DateTimeField()),
                ('panel_members', models.TextField(blank=True, default='', help_text='Comma-separated names of panel members')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('outcome', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='hrm.disciplinarycase')),
            ],
            options={
                'verbose_name': 'Disciplinary Hearing',
                'verbose_name_plural': 'Disciplinary Hearings',
                'ordering': ['-hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_date', models.DateField()),
                ('grounds', models.TextField(help_text='Reasons for the appeal')),
                ('supporting_evidence', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Upheld', 'Upheld'), ('Overturned', 'Overturned'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='hrm.disciplinaryaction')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disciplinary Appeal',
                'verbose_name_plural': 'Disciplinary Appeals',
                'ordering': ['-appeal_date'],
            },
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hrm.disciplinarycase'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
