# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_goodsreceiptitem_purchaseorderitem_quotationlineitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='goodsreceipt',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='rfq',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='firestore_id',
        ),
    ]
