"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY in your .env file — never use the insecure fallback in production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-rl*%45#gc&#p8i+#+qjkc91)5kz8s^7yj7ls7pw0p9xha#vs8n')

# Superuser credentials for Firestore admin bootstrap.
# Override via ADMIN_PASSWORD in .env or Render env vars.
# Used only ONCE when the admin Firestore document does not exist.
ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD', 'IntrexAdmin2026!')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@intrex.com')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd Party
    'rest_framework',
    'django_filters',
    'corsheaders',

    # Core
    'config',

    # Custom Apps
    'billing',
    'frontend',
    'hrm',
    'inventory',
    'investment',
    'solutions',
    'training',
    'accounts',

    # Cross-Module Linking
    'registry',
    'workflow',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'config.middleware.DynamicCsrfMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.ActiveSessionMiddleware',
    'config.tenants.TenantMiddleware',
    'config.spa_middleware.SPAFragmentMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_modules',
                'config.context_processors.vite_assets',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Cache — LocMemCache for single-process deployments.
# For multi-worker production, switch to Redis:
#   pip install django-redis
#   CACHES = {'default': {'BACKEND': 'django_redis.cache.RedisCache', 'LOCATION': 'redis://127.0.0.1:6379/1'}}
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'intrex-erp-cache',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'static/dist',  # Vite build output
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Used by collectstatic for deployment


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'erp_dashboard'
LOGOUT_REDIRECT_URL = 'frontend:index'

AUTHENTICATION_BACKENDS = [
    'accounts.auth_backend.FirestoreBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# CSRF Trusted Origins Configuration
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Automatically add allowed hosts to CSRF trusted origins to ease deployment
for host in ALLOWED_HOSTS:
    if host and host != '*' and not host.startswith(('http://', 'https://')):
        CSRF_TRUSTED_ORIGINS.append(f"https://{host}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{host}")

# CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS.copy()

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
}

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Dhaka'
CELERY_BEAT_SCHEDULE = {
    'cleanup-inactive-sessions': {
        'task': 'config.tasks.cleanup_inactive_sessions',
        'schedule': 3600,
    },
    'send-installment-reminders': {
        'task': 'config.tasks.send_installment_reminders',
        'schedule': 86400,
    },
    'auto-post-due-journals': {
        'task': 'config.tasks.auto_post_due_journals',
        'schedule': 43200,
    },
}

# Detect Render Environment
render_url = os.environ.get('RENDER_EXTERNAL_URL')
if render_url:
    CSRF_TRUSTED_ORIGINS.append(render_url)
    hostname = render_url.replace('https://', '').replace('http://', '')
    if hostname:
        CSRF_TRUSTED_ORIGINS.append(f"https://{hostname}")
        CSRF_TRUSTED_ORIGINS.append(f"http://{hostname}")

# Guarantee origin check passes for user's specific Render domain
CSRF_TRUSTED_ORIGINS.extend([
    "https://erp-intrex-digital.onrender.com",
    "http://erp-intrex-digital.onrender.com",
])

# Vite dev server
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        "http://localhost:5173",
    ])
