# Generated by Django 4.2.30 on 2026-07-06 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('investor_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Institutional', 'Institutional')], default='Individual', max_length=50)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('tax_id', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('bank_routing_code', models.CharField(blank=True, default='', max_length=100)),
                ('contact_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('investor_name', models.CharField(max_length=255)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Interest Rate (%)')),
                ('tenure_months', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Fully Paid', 'Fully Paid'), ('Defaulted', 'Defaulted')], default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='investment.investor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('investor_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('Capital Influx', 'Capital Influx'), ('Capital Withdrawal', 'Capital Withdrawal'), ('Interest Payout', 'Interest Payout'), ('Dividend Payout', 'Dividend Payout')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_method', models.CharField(choices=[('Bank Wire', 'Bank Wire'), ('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Mobile Banking', 'Mobile Banking')], default='Bank Wire', max_length=50)),
                ('value_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Failed', 'Failed')], default='Cleared', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment.investor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundPlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('project_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('Subsidiary', 'Subsidiary'), ('Joint Venture', 'Joint Venture'), ('Investment Fund', 'Investment Fund'), ('Other', 'Other')], default='Subsidiary', max_length=50)),
                ('allocated_capital', models.DecimalField(decimal_places=2, max_digits=16)),
                ('current_valuation', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('roi_expected_annual', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Expected Annual ROI (%)')),
                ('placement_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Divested', 'Divested'), ('Suspended', 'Suspended')], default='Active', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outbound Placement',
                'verbose_name_plural': 'Outbound Placements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('installment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('scheduled_principal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('scheduled_interest', models.DecimalField(decimal_places=2, max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=50)),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='investment.loan')),
            ],
            options={
                'verbose_name': 'Loan Schedule',
                'verbose_name_plural': 'Loan Schedules',
                'ordering': ['loan', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInstrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('instrument_code', models.CharField(max_length=100, unique=True)),
                ('instrument_type', models.CharField(choices=[('Common Stock', 'Common Stock'), ('Preferred Stock', 'Preferred Stock'), ('Corporate Bond', 'Corporate Bond'), ('Government Bond', 'Government Bond'), ('Mutual Fund', 'Mutual Fund'), ('Other', 'Other')], default='Common Stock', max_length=50, verbose_name='Type')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('coupon_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Coupon Rate (%)')),
                ('total_units_issued', models.IntegerField()),
                ('units_outstanding', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Instrument',
                'verbose_name_plural': 'Financial Instruments',
                'ordering': ['instrument_code'],
            },
        ),
        migrations.CreateModel(
            name='PLLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firestore_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('month', models.CharField(max_length=7, verbose_name='Month (YYYY-MM)')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('opex', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('interest_expense', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P&L Ledger Entry',
                'verbose_name_plural': 'P&L Ledger Entries',
                'ordering': ['-month'],
                'unique_together': {('month',)},
            },
        ),
    ]
