# Generated by Django 5.2.15 on 2026-07-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='kyc_document_url',
        ),
        migrations.AddField(
            model_name='investor',
            name='kyc_document',
            field=models.FileField(blank=True, upload_to='kyc/'),
        ),
    ]
