# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_remove_investor_kyc_document_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeaccrual',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='financialinstrument',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='instrumentprice',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='investorholding',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='navhistory',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='outboundplacement',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='plledger',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='firestore_id',
        ),
    ]
