# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='projectrequisition',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='projectstakeholder',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='softwarelicense',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='firestore_id',
        ),
    ]
