# Generated by Django 4.2.30 on 2026-07-06 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(help_text='e.g. hrm, inventory, billing', max_length=50)),
                ('entity_type', models.CharField(help_text='e.g. leave, requisition, invoice', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('module', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, help_text='Firestore doc ID or entity key', max_length=255)),
                ('entity_label', models.CharField(blank=True, help_text='Human-readable label for the entity', max_length=255)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Arbitrary data attached to the instance')),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('color', models.CharField(default='secondary', help_text='Bootstrap color class', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='workflow.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'state_key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_from', to='workflow.workflowstate')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflow.workflowinstance')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_to', to='workflow.workflowstate')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='current_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflow.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='workflow.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(help_text='action name, e.g. approve, reject', max_length=100)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('requires_approval', models.BooleanField(default=False)),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='List of group names allowed to trigger')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='workflow.workflowstate')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.workflowdefinition')),
            ],
            options={
                'unique_together': {('workflow', 'from_state', 'trigger')},
            },
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['workflow', 'entity_id'], name='workflow_wo_workflo_51f8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinstance',
            index=models.Index(fields=['is_active'], name='workflow_wo_is_acti_457ddb_idx'),
        ),
    ]
