# Generated by Django 4.2.30 on 2026-07-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_organization_created_by_organization_updated_by_and_more'),
        ('workflow', '0002_workflowdefinition_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='registry.organization'),
        ),
        migrations.AddField(
            model_name='workflowlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='registry.organization'),
        ),
    ]
