# Generated by Django 5.2.15 on 2026-07-11 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_paymentinstallment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambassador',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='jobplacement',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='firestore_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='firestore_id',
        ),
    ]
